### PR TITLE
feat: gamepath detection

### LINKED ISSUE #33: Game path detection
# Problem

Asking user for their home directory might be excess or can lead to some confusion, so I suggest some gamepath detection to ps script could be added.

## Possible Solution

I've spotted that wuwa launcher leaves a registry entry after installation, which contains game path. It could be obtained automatically without any user input. I once developed something similar in my genshin import scripts, it should be similar ig. 

So with slight modification to your import script, it can bypass the path selection step. I've checked on some friends pc's and that record was in 8 out 8 cases, however maybe some further investigation needed. 

It can be obtained by this powershell command
```powershell
 (Get-ItemProperty -Path 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\KRInstall Wuthering Waves Overseas' -Name InstallPath).InstallPath
```
## Additional Context or Screenshots
image

P.S let me know if you need any help with that, I would happy to assist you with modifying existing script!

### PR DESCRIPTION
**Pull request by teheidoma**
## Problem Context

Asking user for their home directory might be excess or can lead to some confusion, so I suggest some gamepath detection to ps script could be added.

## Solution

updated powershell script in [/scripts/get-url.ps1](https://github.com/Luzefiru/wuwatracker/blob/main/scripts/get-url.ps1) and [createImportScript.ts](https://github.com/Luzefiru/wuwatracker/blob/main/src/lib/createImportScript.ts)

## Testing

1. if registry key exists
image
2. if registry key does not exists
image

## Closing Issues
closes #33

### CODE REVIEW

**Comment by teheidoma** [comment]
Also I take a liberty to slightly modify the ui (removed excess step in import). Please could you check it yourself, I not very familiar with react and afraid to break something :(

image

**Comment by Luzefiru** [comment]
Testing this right now. If this is approved, I'll need to expedite #25 to have a proper video tutorial.

**Comment by Luzefiru** [comment]
### My Info
I'm on Windows 10 (ver 10.0.19045 Build 19045) and I installed Wuthering Waves via **Epic Games**.

It doesn't work on my end, but the extra prompt for the manual input works though. On the other hand, my friends (who installed the game via the official website and not Epic Games) were able to use it without issue.

Here's a (cropped) screenshot of my registry. `KRInstall Wuthering Waves Overseas` doesn't seem to exist for me.
image

### Moving Forward
We'll have to check for path consistencies between Wuthering Waves, both installed via Epic Games & their Offical Website, and try to see if we can find a way to check for both the registry path OR the epic games installation directory to get the logs.

Otherwise, if we can get a significant amount of confirmation from Offical Website players that your script works, we can probably make 2 different tutorial pages, and make a navigation tab for people to choose which tutorial to follow (similar to Star Rail Station:
image

For now, the current tutorial, albeit a hassle, works flexibly across different install sources, so we'll keep it until we find a more user-friendly way to do this.

If you find alternative methods, please let me know.

**Comment by teheidoma** [comment]
Hmm good observation! I think we could have some workaround in case of egs.. I've researched it for a bit, seems like we can't get an installed game list via webprotocol/api/registry :(

But I've got an idea what if we ask user to open the game when executing a script, so it can ger process list, filter out wuwa executable and find its path? Looks doable and universal since the executable file always has the same name
image


@Luzefiru What do you think?

**Comment by Luzefiru** [comment]
Looks like a promising approach! Let's start testing it out once you have the script. 🚀

I have a lot of testers using the Official Website installation on my end. We just need more from the Epic Games side (me included).

Looking forward to it! 🍻

**Comment by Sven-Lyco** [comment]
I detected a typo, that isn't in this PR. Please rename `src/types/LangaugeCode.ts` into `src/types/LanguageCode.ts`

**Comment by Luzefiru** [comment]
> I detected a typo, that isn't in this PR. Please rename `src/types/LangaugeCode.ts` into `src/types/LanguageCode.ts`

Will create a quick patch for this, thanks @Sven-Lyco!

**Comment by Renari** [comment]
For me the proposed powershell solution doesn't return anything.

```
Get-Process "Wuthering Waves"

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    110       8     1740         44       0.02 274932   1 Wuthering Waves

```

**Comment by teheidoma** [comment]
@Renari Yeah that the main issue I'm facing with this approach. Seems like script needs process elevation (admin rights) to get a path from other processes which run from adm user. Currently searching for some bypass or perhaps other solution

**Pull request closed without merging**
