### PR TITLE
feat: add support for chinese server

### PR DESCRIPTION
**Pull request by timas130**
~~**IMPORTANT: Please do not create a Pull Request without creating an issue first.**~~

~~_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._~~

^ bruh, why so serious

## Problem Context

Chinese server URLs don't work

## Solution

Make them work by looking at `svr_area` in the parameters.

## Testing

Testing URL: `https://aki-gm-resources.aki-game.com/aki/gacha/index.html#/record?svr_id=76402e5b20be2c39f095a152090afddc&player_id=106344755&lang=en&gacha_id=4&gacha_type=6&svr_area=cn&record_id=1bff042a4fbd353bc361ac33cd6adebf&resources_id=917dfa695d6c6634ee4e972bb9168f6a`

## Closing Issues

None

### CODE REVIEW

**Comment by Luzefiru** [comment]
The test URL you provided works on a remote branch I've been working on @ #52.

Could you try to verify if it works there?

**Comment by timas130** [comment]
@Luzefiru It does not. The Chinese server uses a completely different URL for fetching the data. It's `.com` instead of `.net`.

**Review by Luzefiru — APPROVED** [review]
@timas130, you're right, my apologies. Good catch and thank you for your help!

**Comment by timas130** [comment]
No problem, sorry for not checking the staging branch.

**Comment by timas130** [comment]
@Luzefiru I noticed you switched up the import script to [a Gist](https://gist.github.com/Luzefiru/19c0759bea1b9e7ef480bb39303b3f6c/), however it doesn't work on Chinese servers, because the .com/.net difference is not the only one in the domain.

The Chinese domain is `aki-gm-resources.aki-game.com`. It doesn't have the `-overseas` suffix

**Comment by Luzefiru** [comment]
> @Luzefiru I noticed you switched up the import script to [a Gist](https://gist.github.com/Luzefiru/19c0759bea1b9e7ef480bb39303b3f6c/), however it doesn't work on Chinese servers, because the .com/.net difference is not the only one in the domain.
> 
> The Chinese domain is `aki-gm-resources.aki-game.com`. It doesn't have the `-overseas` suffix

Ah, my bad. I didn't notice that. I'm creating a fix ASAP. Thanks once again.

**Comment by Luzefiru** [comment]
I have updated the automatic script to match the following regex pattern:
- `https://aki-gm-resources(-oversea)?\.aki-game\.(net|com)`

Could you please confirm if it's working on your end, @timas130?

**Comment by timas130** [comment]
@Luzefiru Works perfectly now, thanks for the quick fix.

**Pull request merged**
