### PR TITLE
Update events.ts

### PR DESCRIPTION
**Pull request by antisocial93**
Changed event dates of ToA, changed some pics sources from my repo to snipboard, and took commit from [PR#83](https://github.com/Luzefiru/wuwatracker/pull/83) with asked changes(it seems that @Kryst4lize forgot about this PR).

Closes #83

### CODE REVIEW

**Comment by Luzefiru** [comment]
Thanks @antisocial93! Can you please add `Closes #83` in your PR body text?

**Comment by antisocial93** [comment]
> Thanks @antisocial93! Can you please add `Closes #83` in your PR body text?

Sure! I was thinking that it will close issue#83 if such exists.

**Comment by Luzefiru** [comment]
> > Thanks @antisocial93! Can you please add `Closes #83` in your PR body text?
> 
> Sure! I was thinking that it will close issue#83 if such exists.

Yeah, it does. Here are the docs for it: [Linking a Pull Request to an Issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by Kryst4lize** [comment]
okay

**Comment by Kryst4lize** [comment]
By the way, I'm sorry for the late reply. Can we automatically update some recurring events like ToA? Also, where can I discuss this repo with other contributors

**Comment by Luzefiru** [comment]
> By the way, I'm sorry for the late reply. Can we automatically update some recurring events like ToA? Also, where can I discuss this repo with other contributors

We're still working on other things for global statistics & (maybe) internationalization before we proceed to rework the timeline. Some contributors hang out and chat in our [Discord Server](https://discord.gg/mADnEXwZGT). We'd love you to stop by!

**Pull request merged**
